### ISSUE TITLE
Download button produces the wrong json

### ISSUE THREAD

**Issue by stavshamir** [springwolf/springwolf-ui#27]
![image](https://user-images.githubusercontent.com/22257261/197408158-2ac8be97-3b93-4368-ac19-e48c38d8986b.png)

Clicking the download button produces the wrong json - instead of the async api doc, it gives the mapped version used by the UI.

**Comment by stavshamir** [comment]
@timonback Please let me know if you have time to fix this, if not I will try to squeeze it in tomorrow. I will wait with the release until we finish it.

**Comment by timonback** [comment]
Good catch, PR is linked. We need to investigate UI test frameworks to catch this, but this is a future task for now.

**Comment by stavshamir** [comment]
Definitely need to add unit tests
