### ISSUE TITLE
type of element in arrays

### ISSUE THREAD

**Issue by f-m-t-t-m** [springwolf/springwolf-ui#31]
UI doesn't display type of elements in arrays
![image](https://user-images.githubusercontent.com/73017769/197701750-0d4fe22a-c1ca-4b4c-8699-20ea82695b97.png)

**Comment by stavshamir** [comment]
The generated schema for a list looks like this:
```json
{
    "type" : "array",
    "exampleSetFlag" : false,
    "items" : {
      "type" : "string",
      "exampleSetFlag" : false,
      "types" : [ "string" ]
    },
    "types" : [ "array" ]
}
```

The type is `array` and the `items` contain the type `string`. So the UI has the info needed, but it is not displayed.
